apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRESQL_USER: myuser
  POSTGRESQL_PASSWORD: mypassword
  POSTGRESQL_DATABASE: mydb
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: postgres
 labels:
   app: postgres
spec:
 replicas: 1
 selector:
   matchLabels:
     app: postgres
 template:
   metadata:
     labels:
       app: postgres
   spec:
     containers:
       - name: postgres
         image: 'image-registry.openshift-image-registry.svc:5000/openshift/postgresql@sha256:ed2da0eed3f495f5455f490cdf7f7943420f64b0cf541271a2d315a3f9e9744c'
         ports:
           - containerPort: 5432
         env:
           - name: POSTGRESQL_USER
             valueFrom:
               secretKeyRef:
                 name: postgres-secret
                 key: POSTGRESQL_USER
           - name: POSTGRESQL_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: postgres-secret
                 key: POSTGRESQL_PASSWORD
           - name: POSTGRESQL_DATABASE
             valueFrom:
               secretKeyRef:
                 name: postgres-secret
                 key: POSTGRESQL_DATABASE
         volumeMounts:
           - name: postgresql-data
             mountPath: /var/lib/postgresql/data
     volumes:
       - name: postgresql-data
         persistentVolumeClaim:
           claimName: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    name: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432