apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: shortify-rabbitmq
 labels:
   app: shortify-rabbitmq
spec:
 replicas: 1
 selector:
   matchLabels:
     app: shortify-rabbitmq
 template:
   metadata:
     labels:
       app: shortify-rabbitmq
   spec:
     containers:
       - name: rabbitmq
         image: rabbitmq:3-management
         ports:
           - containerPort: 5672
           - containerPort: 15672  # Management UI
         env:
           - name: RABBITMQ_DEFAULT_USER
             valueFrom:
               secretKeyRef:
                 name: rabbitmq-secret
                 key: RABBITMQ_DEFAULT_USER
           - name: RABBITMQ_DEFAULT_PASS
             valueFrom:
               secretKeyRef:
                 name: rabbitmq-secret
                 key: RABBITMQ_DEFAULT_PASS
         volumeMounts:
           - name: rabbitmq-data
             mountPath: /var/lib/rabbitmq
     volumes:
       - name: rabbitmq-data
         emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: shortify-rabbitmq
spec:
  selector:
    app: shortify-rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672