apiVersion: apps/v1
kind: Deployment
metadata:
 name: shortify-redis
 labels:
   app: shortify-redis
spec:
 replicas: 1
 selector:
   matchLabels:
     app: shortify-redis
 template:
   metadata:
     labels:
       app: shortify-redis
   spec:
     containers:
       - name: redis
         image: redis:7
         ports:
           - containerPort: 6379
         volumeMounts:
           - name: redis-data
             mountPath: /data
     volumes:
       - name: redis-data
         emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
 name: shortify-redis
spec:
 selector:
   app: shortify-redis
 ports:
   - protocol: TCP
     port: 6379
     targetPort: 6379      