kind: Deployment
apiVersion: apps/v1
metadata:
  name: shortify
  namespace: shortify
  labels:
    app: shortify
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: shortify
  template:
    metadata:
      labels:
        app: shortify
    spec:
      containers:
        - name: shortify
          image: docker.io/rajprajapati/shortify:latest
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              value: Host=postgres;Port=5432;Database=mydb;Username=myuser;Password=mypassword
            - name: ConnectionStrings__RedisConnection
              value: 'redis:6379'
            - name: ConnectionStrings__RabbitMQConnection
              value: 'amqp://guest:guest@rabbitmq:5672'
---
apiVersion: v1
kind: Service
metadata:
  name: shortify-service
spec:
  selector:
    app: shortify
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
